[package]
name = "uart"
version = "0.1.0"
authors = ["Uniarts Developers"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "uart"
path = "src/main.rs"

[dependencies]
futures         = { version = "=0.3.8" }
parity-util-mem = { version = "*", default-features = false, features = ["jemalloc-global"] }

uniarts-cli = { path = "cli" }
uniarts-service = { path = "service" }
uniarts-rpc = { path = "rpc" }
pangu-runtime = { path = "../runtime/pangu", optional = true }
fuxi-runtime = { path = "../runtime/fuxi", optional = true }
