  
[profile.release]
panic = 'unwind'

[workspace]
members = [
    'runtime',
    'node',
    'primitives',
    'pallets/assets',
    'pallets/nft',
    'pallets/token',
    'pallets/trade',
    'pallets/validator-set'
]