[package]
name = "uniarts-rpc"
description = "Uniarts node rpc"
version = "1.0.0"
authors = ["terry.tu <tuminfei1981@gmail.com>"]
edition = "2018"

[dependencies]
# crates
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false }
jsonrpc-core = "15.1.0"

# uniarts
uniarts-primitives = { path = "../../primitives" }

# rpc
substrate-frame-rpc-system = { version = "2.0.0" }
pallet-transaction-payment-rpc = { version = "2.0.0" }

pallet-staking-rpc = { path = "../../pallets/staking/rpc" }
pallet-contracts-rpc = { version = "0.8.0" }

# substrate client
sc-cli = { version = "0.8.0", features = ["wasmtime"] }
sc-executor = { version = "0.8.0", features = ["wasmtime"] }
sc-service = { version = "0.8.0", features = ["wasmtime"] }
sc-transaction-pool = { version = "2.0.0" }
sc-consensus-aura = { version = "0.8.0" }
sc-consensus = { version = "0.8.0" }
sc-finality-grandpa = { version = "0.8.0" }
sc-client-api = { version = "2.0.0" }
sc-rpc = { version = "2.0.0" }
sc-rpc-api = { version = "0.8.0" }
sc-telemetry = { version = "2.0.0" }
sc-basic-authorship = { version = "0.8.0" }

# substrate primitives
sp-core = { version = "2.0.0" }
sp-inherents = { version = "2.0.0" }
sp-transaction-pool = { version = "2.0.0"}
sp-consensus-aura = { version = "0.8.0" }
sp-consensus = { version = "0.8.0" }
sp-finality-grandpa = { version = "2.0.0" }
sp-runtime = { version = "2.0.0" }
sp-api = { version = "2.0.0" }
sp-blockchain = { version = "2.0.0" }
sp-block-builder = { version = "2.0.0" }